path: /Users/weixianfu/Documents/Datas/mtsd
path_sliced_resized: /Users/weixianfu/Documents/Datas/mtsd-resized
train: train_full/images
val: val/images
nc: 401
names:
  0: warning--traffic-merges-right--g1
  1: warning--added-lane-right--g1
  2: warning--playground--g1
  3: other-sign
  4: regulatory--no-stopping--g15
  5: regulatory--priority-road--g4
  6: warning--pedestrian-stumble-train--g1
  7: regulatory--maximum-speed-limit-45--g3
  8: regulatory--stop--g1
  9: warning--railroad-crossing--g1
  10: information--end-of-built-up-area--g1
  11: regulatory--pedestrians-only--g1
  12: regulatory--no-entry--g1
  13: regulatory--one-way-straight--g1
  14: complementary--maximum-speed-limit-15--g1
  15: regulatory--keep-right--g4
  16: regulatory--yield--g1
  17: warning--pedestrians-crossing--g10
  18: regulatory--reversible-lanes--g2
  19: regulatory--turn-left--g2
  20: regulatory--no-parking--g2
  21: regulatory--one-way-right--g1
  22: regulatory--one-way-left--g1
  23: warning--divided-highway-ends--g1
  24: regulatory--maximum-speed-limit-55--g2
  25: information--pedestrians-crossing--g1
  26: regulatory--no-right-turn--g1
  27: information--tram-bus-stop--g2
  28: regulatory--turn-right-ahead--g1
  29: regulatory--no-overtaking--g1
  30: regulatory--height-limit--g1
  31: warning--domestic-animals--g3
  32: warning--traffic-merges-left--g1
  33: regulatory--maximum-speed-limit-35--g2
  34: regulatory--keep-right--g1
  35: complementary--priority-route-at-intersection--g1
  36: warning--texts--g1
  37: complementary--maximum-speed-limit-20--g1
  38: information--disabled-persons--g1
  39: warning--crossroads--g1
  40: regulatory--no-parking--g1
  41: warning--roadworks--g1
  42: complementary--turn-left--g2
  43: warning--double-curve-first-right--g1
  44: regulatory--turn-left-ahead--g1
  45: information--parking--g1
  46: regulatory--no-motorcycles--g1
  47: complementary--chevron-left--g2
  48: complementary--chevron-left--g3
  49: complementary--chevron-right--g3
  50: information--end-of-motorway--g1
  51: regulatory--maximum-speed-limit-50--g1
  52: warning--texts--g3
  53: warning--junction-with-a-side-road-acute-left--g1
  54: regulatory--no-heavy-goods-vehicles--g2
  55: regulatory--roundabout--g1
  56: warning--texts--g2
  57: warning--pedestrians-crossing--g4
  58: complementary--keep-left--g1
  59: warning--slippery-road-surface--g1
  60: warning--double-curve-first-right--g2
  61: regulatory--no-parking--g5
  62: complementary--obstacle-delineator--g2
  63: regulatory--keep-left--g1
  64: warning--railroad-crossing-without-barriers--g4
  65: complementary--chevron-left--g1
  66: regulatory--end-of-prohibition--g1
  67: warning--junction-with-a-side-road-perpendicular-right--g1
  68: complementary--obstacle-delineator--g1
  69: regulatory--maximum-speed-limit-45--g1
  70: regulatory--weight-limit--g1
  71: warning--slippery-road-surface--g2
  72: complementary--distance--g3
  73: warning--junction-with-a-side-road-perpendicular-left--g3
  74: regulatory--go-straight--g1
  75: information--road-bump--g1
  76: warning--children--g1
  77: regulatory--maximum-speed-limit-40--g1
  78: regulatory--no-buses--g3
  79: regulatory--no-heavy-goods-vehicles--g4
  80: complementary--chevron-right-unsure--g6
  81: complementary--chevron-right--g5
  82: complementary--chevron-right--g1
  83: information--stairs--g1
  84: warning--curve-right--g1
  85: regulatory--maximum-speed-limit-30--g1
  86: complementary--pass-right--g1
  87: complementary--chevron-right--g4
  88: warning--t-roads--g1
  89: regulatory--no-u-turn--g2
  90: warning--junction-with-a-side-road-perpendicular-right--g3
  91: warning--horizontal-alignment-right--g1
  92: warning--pedestrians-crossing--g1
  93: regulatory--keep-left--g2
  94: warning--wombat-crossing--g1
  95: regulatory--no-hawkers--g1
  96: warning--railroad-crossing-with-barriers--g1
  97: warning--uneven-road--g2
  98: complementary--extent-of-prohibition-area-both-direction--g1
  99: warning--t-roads--g2
  100: regulatory--turn-left--g1
  101: regulatory--turn-left--g3
  102: warning--roundabout--g1
  103: information--parking--g3
  104: regulatory--turn-right--g2
  105: regulatory--no-motor-vehicles--g4
  106: regulatory--shared-path-pedestrians-and-bicycles--g1
  107: regulatory--no-overtaking--g5
  108: regulatory--maximum-speed-limit-5--g1
  109: complementary--go-left--g1
  110: warning--double-curve-first-left--g1
  111: regulatory--go-straight-or-turn-left--g2
  112: regulatory--turn-right--g3
  113: information--interstate-route--g1
  114: regulatory--lane-control--g1
  115: warning--road-bump--g2
  116: warning--roadworks--g3
  117: regulatory--one-way-left--g3
  118: warning--narrow-bridge--g1
  119: complementary--maximum-speed-limit-50--g1
  120: warning--curve-left--g2
  121: regulatory--maximum-speed-limit-100--g1
  122: regulatory--maximum-speed-limit-120--g1
  123: information--dead-end--g1
  124: complementary--maximum-speed-limit-55--g1
  125: warning--junction-with-a-side-road-acute-right--g1
  126: regulatory--maximum-speed-limit-70--g1
  127: regulatory--no-u-turn--g3
  128: regulatory--no-right-turn--g2
  129: regulatory--no-stopping--g5
  130: warning--roadworks--g2
  131: complementary--go-right--g1
  132: warning--wild-animals--g4
  133: regulatory--maximum-speed-limit-60--g1
  134: information--bike-route--g1
  135: information--food--g2
  136: regulatory--go-straight-or-turn-left--g3
  137: regulatory--turn-right-ahead--g2
  138: regulatory--no-stopping--g2
  139: regulatory--give-way-to-oncoming-traffic--g1
  140: warning--children--g2
  141: complementary--maximum-speed-limit-35--g1
  142: warning--road-bump--g1
  143: regulatory--no-u-turn--g1
  144: warning--pass-left-or-right--g2
  145: regulatory--no-overtaking--g2
  146: regulatory--turn-right--g1
  147: warning--curve-right--g2
  148: regulatory--no-turns--g1
  149: regulatory--no-turn-on-red--g3
  150: regulatory--no-parking-or-no-stopping--g2
  151: regulatory--stop-here-on-red-or-flashing-light--g2
  152: regulatory--maximum-speed-limit-25--g2
  153: warning--junction-with-a-side-road-perpendicular-left--g1
  154: warning--winding-road-first-right--g1
  155: warning--accidental-area-unsure--g2
  156: regulatory--no-overtaking--g4
  157: warning--school-zone--g2
  158: regulatory--wrong-way--g1
  159: regulatory--road-closed--g2
  160: regulatory--no-stopping--g8
  161: complementary--distance--g1
  162: warning--emergency-vehicles--g1
  163: warning--kangaloo-crossing--g1
  164: complementary--maximum-speed-limit-30--g1
  165: warning--turn-right--g1
  166: regulatory--truck-speed-limit-60--g1
  167: regulatory--priority-over-oncoming-vehicles--g1
  168: information--pedestrians-crossing--g2
  169: information--parking--g5
  170: information--children--g1
  171: regulatory--passing-lane-ahead--g1
  172: regulatory--no-motor-vehicles-except-motorcycles--g2
  173: information--safety-area--g2
  174: warning--roundabout--g25
  175: regulatory--no-left-turn--g1
  176: warning--roadworks--g4
  177: complementary--trucks--g1
  178: regulatory--go-straight--g3
  179: warning--steep-ascent--g7
  180: warning--divided-highway-ends--g2
  181: information--parking--g45
  182: regulatory--buses-only--g1
  183: regulatory--maximum-speed-limit-20--g1
  184: warning--road-narrows--g1
  185: warning--road-narrows-left--g1
  186: complementary--accident-area--g3
  187: warning--other-danger--g1
  188: regulatory--one-way-left--g2
  189: warning--road-narrows-left--g2
  190: warning--trucks-crossing--g1
  191: regulatory--bicycles-only--g1
  192: complementary--maximum-speed-limit-70--g1
  193: warning--curve-left--g1
  194: warning--domestic-animals--g1
  195: regulatory--maximum-speed-limit-30--g3
  196: warning--road-narrows-right--g2
  197: regulatory--keep-right--g6
  198: information--living-street--g1
  199: complementary--tow-away-zone--g1
  200: regulatory--triple-lanes-turn-left-center-lane--g1
  201: regulatory--maximum-speed-limit-90--g1
  202: complementary--both-directions--g1
  203: complementary--maximum-speed-limit-45--g1
  204: warning--turn-left--g1
  205: information--limited-access-road--g1
  206: regulatory--no-heavy-goods-vehicles--g1
  207: regulatory--maximum-speed-limit-80--g1
  208: complementary--maximum-speed-limit-75--g1
  209: regulatory--dual-lanes-go-straight-on-right--g1
  210: regulatory--do-not-block-intersection--g1
  211: regulatory--radar-enforced--g1
  212: warning--traffic-merges-right--g2
  213: regulatory--stop--g10
  214: regulatory--go-straight-or-turn-left--g1
  215: regulatory--no-straight-through--g2
  216: regulatory--end-of-maximum-speed-limit-70--g2
  217: regulatory--minimum-safe-distance--g1
  218: regulatory--no-turn-on-red--g1
  219: regulatory--stop-signals--g1
  220: information--gas-station--g1
  221: regulatory--end-of-speed-limit-zone--g1
  222: warning--two-way-traffic--g1
  223: warning--railroad-crossing-without-barriers--g3
  224: information--hospital--g1
  225: warning--stop-ahead--g9
  226: warning--railroad-crossing--g3
  227: information--motorway--g1
  228: information--emergency-facility--g2
  229: warning--road-widens--g1
  230: regulatory--road-closed-to-vehicles--g3
  231: information--highway-exit--g1
  232: regulatory--no-turn-on-red--g2
  233: regulatory--no-pedestrians--g2
  234: regulatory--width-limit--g1
  235: warning--hairpin-curve-right--g1
  236: complementary--keep-right--g1
  237: warning--junction-with-a-side-road-perpendicular-left--g4
  238: warning--flaggers-in-road--g1
  239: warning--wild-animals--g1
  240: warning--traffic-signals--g4
  241: warning--crossroads--g3
  242: warning--two-way-traffic--g2
  243: warning--traffic-signals--g2
  244: regulatory--one-way-right--g2
  245: regulatory--no-overtaking-by-heavy-goods-vehicles--g1
  246: complementary--distance--g2
  247: warning--double-reverse-curve-right--g1
  248: regulatory--one-way-right--g3
  249: warning--double-curve-first-left--g2
  250: complementary--except-bicycles--g1
  251: warning--traffic-signals--g1
  252: complementary--chevron-left--g5
  253: warning--road-widens-right--g1
  254: regulatory--maximum-speed-limit-40--g6
  255: warning--horizontal-alignment-left--g1
  256: regulatory--no-bicycles--g1
  257: regulatory--maximum-speed-limit-15--g1
  258: regulatory--no-straight-through--g1
  259: regulatory--parking-restrictions--g2
  260: regulatory--no-parking-or-no-stopping--g1
  261: warning--uneven-road--g6
  262: complementary--go-right--g2
  263: warning--railroad-intersection--g3
  264: warning--railroad-crossing--g4
  265: information--airport--g2
  266: complementary--trucks-turn-right--g1
  267: regulatory--end-of-bicycles-only--g1
  268: warning--road-narrows--g2
  269: warning--pedestrians-crossing--g5
  270: regulatory--maximum-speed-limit-led-60--g1
  271: regulatory--no-parking-or-no-stopping--g3
  272: regulatory--pedestrians-only--g2
  273: warning--slippery-motorcycles--g1
  274: regulatory--pass-on-either-side--g2
  275: complementary--one-direction-right--g1
  276: warning--pedestrians-crossing--g9
  277: regulatory--go-straight-or-turn-right--g1
  278: information--end-of-living-street--g1
  279: information--bus-stop--g1
  280: warning--winding-road-first-left--g1
  281: warning--bus-stop-ahead--g3
  282: warning--double-turn-first-right--g1
  283: warning--winding-road-first-right--g3
  284: warning--railroad-crossing-with-barriers--g2
  285: regulatory--no-motor-vehicles-except-motorcycles--g1
  286: warning--railroad-intersection--g4
  287: complementary--turn-right--g2
  288: regulatory--keep-right--g2
  289: warning--bicycles-crossing--g2
  290: regulatory--bicycles-only--g2
  291: regulatory--maximum-speed-limit-led-80--g1
  292: warning--height-restriction--g2
  293: regulatory--maximum-speed-limit-50--g6
  294: warning--hairpin-curve-right--g4
  295: warning--traffic-signals--g3
  296: regulatory--mopeds-and-bicycles-only--g1
  297: regulatory--no-left-turn--g2
  298: regulatory--end-of-no-parking--g1
  299: regulatory--end-of-priority-road--g1
  300: regulatory--no-heavy-goods-vehicles-or-buses--g1
  301: warning--uneven-roads-ahead--g1
  302: warning--hairpin-curve-left--g1
  303: information--trailer-camping--g1
  304: regulatory--no-stopping--g4
  305: regulatory--no-pedestrians-or-bicycles--g1
  306: regulatory--no-heavy-goods-vehicles--g5
  307: warning--other-danger--g3
  308: regulatory--dual-lanes-go-straight-on-left--g1
  309: regulatory--u-turn--g1
  310: complementary--maximum-speed-limit-40--g1
  311: regulatory--stop-here-on-red-or-flashing-light--g1
  312: information--parking--g6
  313: regulatory--no-pedestrians--g3
  314: warning--traffic-merges-left--g2
  315: regulatory--text-four-lines--g1
  316: regulatory--road-closed-to-vehicles--g1
  317: regulatory--dual-path-bicycles-and-pedestrians--g1
  318: regulatory--maximum-speed-limit-40--g3
  319: information--parking--g2
  320: warning--bicycles-crossing--g3
  321: regulatory--pass-on-either-side--g1
  322: regulatory--no-bicycles--g3
  323: warning--pass-left-or-right--g1
  324: regulatory--maximum-speed-limit-10--g1
  325: complementary--chevron-left--g4
  326: warning--falling-rocks-or-debris-right--g2
  327: regulatory--maximum-speed-limit-led-100--g1
  328: warning--pedestrians-crossing--g12
  329: complementary--buses--g1
  330: warning--road-narrows-right--g1
  331: information--highway-interstate-route--g2
  332: warning--y-roads--g1
  333: warning--railroad-crossing-without-barriers--g1
  334: warning--narrow-bridge--g3
  335: regulatory--maximum-speed-limit-110--g1
  336: regulatory--no-right-turn--g3
  337: information--telephone--g2
  338: regulatory--stop--g2
  339: regulatory--left-turn-yield-on-green--g1
  340: warning--dual-lanes-right-turn-or-go-straight--g1
  341: regulatory--dual-path-pedestrians-and-bicycles--g1
  342: regulatory--maximum-speed-limit-100--g3
  343: complementary--one-direction-left--g1
  344: regulatory--no-left-turn--g3
  345: regulatory--go-straight-or-turn-right--g3
  346: warning--dip--g2
  347: warning--bicycles-crossing--g1
  348: regulatory--no-motorcycles--g2
  349: regulatory--no-pedestrians--g1
  350: warning--falling-rocks-or-debris-right--g1
  351: warning--winding-road-first-left--g2
  352: regulatory--end-of-maximum-speed-limit-30--g2
  353: warning--loop-270-degree--g1
  354: complementary--maximum-speed-limit-25--g1
  355: warning--falling-rocks-or-debris-right--g4
  356: regulatory--road-closed--g1
  357: regulatory--maximum-speed-limit-65--g2
  358: warning--trail-crossing--g2
  359: regulatory--no-vehicles-carrying-dangerous-goods--g1
  360: information--end-of-limited-access-road--g1
  361: information--lodging--g1
  362: information--telephone--g1
  363: information--central-lane--g1
  364: warning--offset-roads--g3
  365: regulatory--no-motor-vehicle-trailers--g1
  366: regulatory--roundabout--g2
  367: warning--roadworks--g6
  368: warning--crossroads-with-priority-to-the-right--g1
  369: information--no-parking--g3
  370: information--gas-station--g3
  371: regulatory--dual-lanes-turn-right-or-straight--g1
  372: regulatory--maximum-speed-limit-25--g1
  373: regulatory--dual-lanes-turn-left-or-straight--g1
  374: regulatory--no-mopeds-or-bicycles--g1
  375: regulatory--no-bicycles--g2
  376: warning--horizontal-alignment-right--g3
  377: information--camp--g1
  378: warning--pedestrians-crossing--g11
  379: regulatory--no-motor-vehicles--g1
  380: warning--shared-lane-motorcycles-bicycles--g1
  381: information--minimum-speed-40--g1
  382: information--dead-end-except-bicycles--g1
  383: information--airport--g1
  384: regulatory--do-not-stop-on-tracks--g1
  385: warning--turn-right--g2
  386: warning--trams-crossing--g1
  387: warning--railroad-crossing-with-barriers--g4
  388: regulatory--end-of-maximum-speed-limit-70--g1
  389: regulatory--turning-vehicles-yield-to-pedestrians--g1
  390: warning--playground--g3
  391: regulatory--bicycles-only--g3
  392: warning--hairpin-curve-left--g3
  393: regulatory--end-of-buses-only--g1
  394: regulatory--dual-lanes-turn-left-no-u-turn--g1
  395: regulatory--shared-path-bicycles-and-pedestrians--g1
  396: warning--equestrians-crossing--g2
  397: regulatory--weight-limit-with-trucks--g1
  398: regulatory--detour-left--g1
  399: information--end-of-pedestrians-only--g2
  400: warning--restricted-zone--g1
