import shutil, yaml
from pathlib import Path
from typing import Iterable, List, Tuple

import cv2
import numpy as np

def _get_data_config():
    ROOT = Path(__file__).resolve().parents[2]
    DATA_CONFIG = ROOT / "configs" / "data.yaml"
    with open(DATA_CONFIG, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    return cfg

# Global constants
INPUT_PATH = _get_data_config()["path"]
OUTPUT_PATH = _get_data_config()["path_sliced_resized"]
MTSD_TYPES = ("train_full", "train_partial", "val")
TARGET_SIZE = 1280
OVERLAP = 0.2
MIN_ABS_AREA = 200
MIN_AREA_RATIO = 0.6

# return image path of the image with the given name
def _find_image(input_dir: Path, name: str) -> Path:
    return Path(input_dir) / "images" / f"{name}.jpg"

# return labels of the image with the given name
def _find_labels(input_dir: Path, name: str) -> List[str]:
    path = Path(input_dir) / "labels" / f"{name}.txt"
    if not path.exists():
        return []
    with open(path, "r", encoding="utf-8") as f:
        labels = [line.strip() for line in f.readlines() if line.strip()]
    for label in labels:
        cls, cx, cy, bw, bh = label.split()
        cx = float(cx)
        cy = float(cy)
        bw = float(bw)
        bh = float(bh)
        yield cls, cx, cy, bw, bh
    pass

def _prepare_output(target_dir: Path) -> None:
    for name in ("images", "labels"):
        sub = Path(target_dir) / name
        if sub.exists():
            continue
        sub.mkdir(parents=True)

def _write_if_labels(labels: List[str], save_path: Path, save_name: Path, image: np.ndarray) -> None:
    if not labels:
        return
    img_path = save_path / "images" / f"{save_name}.jpg"
    cv2.imwrite(img_path, image)
    label_path = save_path / "labels" / f"{save_name}.txt"
    with open(label_path, "w", encoding="utf-8") as f:
        f.write("\n".join(labels))

def _slice_image(img: np.ndarray, slice_size: int = TARGET_SIZE, overlap: float = OVERLAP) \
    -> List[Tuple[np.ndarray, Tuple[int, int, int, int]]]:
    """
    Slice a large image into overlapping patches.
    
    Parameters:
    -----------
    img : np.ndarray
        The input image to slice, generated by cv2.imread
    slice_size : int
        The size of each slice
    overlap : float
        The overlap between adjacent slices
        
    Returns:
    --------
    List[Tuple[np.ndarray, Tuple[int, int, int, int]]]
        List of (slice_image, (x1, y1, x2, y2)) tuples where coordinates are in original image space.
    """
    h, w = img.shape[:2]
    step = int(slice_size * (1 - overlap))
    slices: List[Tuple[np.ndarray, Tuple[int, int, int, int]]] = []
    y = 0
    while y < h:
        x = 0
        while x < w:
            x2 = min(x + slice_size, w)
            y2 = min(y + slice_size, h)
            x1 = max(0, x2 - slice_size)
            y1 = max(0, y2 - slice_size)
            slices.append((img[y1:y2, x1:x2], (x1, y1, x2, y2)))
            if x2 >= w:
                break
            x += step
        if y2 >= h:
            break
        y += step
    return slices

def _slice_labels_from_slice_box(image_shape: Tuple[int, int], slice_box: Tuple[int, int, int, int],\
labels: Iterable[Tuple[str, float, float, float, float]], \
min_abs_area: int = MIN_ABS_AREA, \
min_area_ratio: float = MIN_AREA_RATIO \
) -> List[str]:
    h, w = image_shape
    sx1, sy1, sx2, sy2 = slice_box
    sw = sx2 - sx1
    sh = sy2 - sy1
    out: List[str] = []
    for cls, cx, cy, bw, bh in labels:
        bx1 = (cx - bw / 2) * w
        by1 = (cy - bh / 2) * h
        bx2 = (cx + bw / 2) * w
        by2 = (cy + bh / 2) * h
        orig_area = (bx2 - bx1) * (by2 - by1)
        ix1 = max(bx1, sx1)
        iy1 = max(by1, sy1)
        ix2 = min(bx2, sx2)
        iy2 = min(by2, sy2)
        if ix2 <= ix1 or iy2 <= iy1:
            continue
        inter_area = (ix2 - ix1) * (iy2 - iy1)
        if inter_area < min_abs_area or inter_area < min_area_ratio * orig_area:
            continue
        rx1 = ix1 - sx1
        ry1 = iy1 - sy1
        rx2 = ix2 - sx1
        ry2 = iy2 - sy1
        rcx = (rx1 + rx2) / 2 / sw
        rcy = (ry1 + ry2) / 2 / sh
        rbw = (rx2 - rx1) / sw
        rbh = (ry2 - ry1) / sh
        out.append(f"{cls} {rcx:.6f} {rcy:.6f} {rbw:.6f} {rbh:.6f}")
    return out

def _transform_labels_for_resized(labels: Iterable[Tuple[str, float, float, float, float]],\
    image_shape: Tuple[int, int], scale: float, pad_x: float, pad_y: float, target: int,\
    min_abs_area: int = MIN_ABS_AREA, min_area_ratio: float = MIN_AREA_RATIO) -> List[str]:
    h, w = image_shape
    left = int(np.floor(pad_x))
    top = int(np.floor(pad_y))
    out: List[str] = []
    for cls, cx, cy, bw, bh in labels:
        px = cx * w * scale + left
        py = cy * h * scale + top
        pw = bw * w * scale
        ph = bh * h * scale
        inter_area = pw * ph
        # print("inter_area: ", inter_area)
        if inter_area < min_abs_area:
            # print("inter_area < min_abs_area: ", inter_area)
            continue
        out.append(f"{cls} {px/target:.6f} {py/target:.6f} {pw/target:.6f} {ph/target:.6f}")
    return out

def _resized_letterbox(img: np.ndarray, target: int) -> Tuple[np.ndarray, float, float, float]:
    h, w = img.shape[:2]
    scale = min(target / w, target / h)
    new_w, new_h = int(round(w * scale)), int(round(h * scale))
    resized = cv2.resize(img, (new_w, new_h), interpolation=cv2.INTER_LINEAR)
    pad_x = (target - new_w) / 2
    pad_y = (target - new_h) / 2
    top, bottom = int(np.floor(pad_y)), int(np.ceil(pad_y))
    left, right = int(np.floor(pad_x)), int(np.ceil(pad_x))
    out = cv2.copyMakeBorder(resized, top, bottom, left, right, cv2.BORDER_CONSTANT, value=(114, 114, 114))
    return out, scale, pad_x, pad_y

def process_image(name: str, input_path: Path = INPUT_PATH+"/"+MTSD_TYPES[0], output_path: Path = OUTPUT_PATH+"/"+MTSD_TYPES[0], \
    target_size: int = TARGET_SIZE, overlap: float = OVERLAP, min_abs_area: int = MIN_ABS_AREA, \
    min_area_ratio: float = MIN_AREA_RATIO) -> None:
    input_path, output_path = Path(input_path), Path(output_path)
    _prepare_output(output_path)
    image_path = _find_image(input_path, name)

    image = cv2.imread(str(image_path))
    if image is None:
        raise ValueError(f"unable to read image: {image_path}")
    image_shape = image.shape[:2]
    label_iter = list(_find_labels(input_path, name))

    slices = _slice_image(image, target_size, overlap)
    for idx, (patch, box) in enumerate(slices):
        slice_labels = _slice_labels_from_slice_box(image_shape=image_shape, slice_box=box, \
            labels=label_iter, min_abs_area=min_abs_area, min_area_ratio=min_area_ratio)
        _write_if_labels(slice_labels, save_path=output_path, save_name=f"{name}_{idx}", image=patch)
    
    # Save resized full image
    resized, scale, pad_x, pad_y = _resized_letterbox(image, target_size)
    resized_name = f"{name}_F"
    resized_labels = _transform_labels_for_resized(label_iter, image_shape, scale, pad_x, pad_y, \
    target_size, min_abs_area, min_area_ratio)
    _write_if_labels(resized_labels, save_path=output_path, save_name=resized_name, image=resized)

    

def _write_image_and_labels(save_path: Path, save_name: str, image: np.ndarray, labels: List[str]) -> None:
    img_path = save_path / "images" / f"{save_name}.jpg"
    cv2.imwrite(str(img_path), image)
    label_path = save_path / "labels" / f"{save_name}.txt"
    with open(label_path, "w", encoding="utf-8") as f:
        f.write("\n".join(labels))

def process_val_image(name: str, input_path: Path = INPUT_PATH+"/"+MTSD_TYPES[2], 
    output_path: Path = OUTPUT_PATH+"/"+MTSD_TYPES[2], 
    target_size: int = TARGET_SIZE, overlap: float = OVERLAP,
    min_abs_area: int = MIN_ABS_AREA, min_area_ratio: float = MIN_AREA_RATIO) -> None:
    """处理val数据集：无条件保存所有切片和F图片，有labels则保存labels"""
    input_path, output_path = Path(input_path), Path(output_path)
    _prepare_output(output_path)
    image_path = _find_image(input_path, name)

    image = cv2.imread(str(image_path))
    if image is None:
        raise ValueError(f"unable to read image: {image_path}")
    image_shape = image.shape[:2]
    label_iter = list(_find_labels(input_path, name))

    # 切分图片
    slices = _slice_image(image, target_size, overlap)
    for idx, (patch, box) in enumerate(slices):
        slice_labels = _slice_labels_from_slice_box(image_shape=image_shape, slice_box=box,
            labels=label_iter, min_abs_area=min_abs_area, min_area_ratio=min_area_ratio)
        _write_image_and_labels(output_path, f"{name}_{idx}", patch, slice_labels)
    
    # 保存resize后的完整图片
    resized, scale, pad_x, pad_y = _resized_letterbox(image, target_size)
    resized_labels = _transform_labels_for_resized(label_iter, image_shape, scale, pad_x, pad_y,
        target_size, min_abs_area, min_area_ratio)
    _write_image_and_labels(output_path, f"{name}_F", resized, resized_labels)


if __name__ == "__main__":
    # temp_path = INPUT_PATH+"/train_full"
    # for label in _find_labels(temp_path, "fully_train___YtZD5n9fhOMe-rzQa5oA"):
    #     print(label)
    process_image(name="fully_train___YtZD5n9fhOMe-rzQa5oA")